### ISSUE TITLE
💄 Improve wlogout View

### ISSUE THREAD

**Issue by purplesmoke05** [purplesmoke05/dotnix#18]
## Overview
Improved the visual appearance of the `wlogout` screen by adjusting CSS properties.

## Changes
- Changed the `background-color` of buttons in `home-manager/wm/hyprland/wlogout/wlogout.css`.
- Added a `margin` to buttons in the same CSS file.

### 833f0ae65f078cbf9d209cb65e9f554841c40740 (💄 Improve wlogout views)
- Updated `wlogout.css` to change button background color and add margin.
  ```css
  /* home-manager/wm/hyprland/wlogout/wlogout.css */
  button {
      /* ... other properties ... */
      /* background-color: #c8c8ff; */
      background-color: #34344a;
      /* ... */
      margin: 1px;
  }
  ```
---
This issue was created using Gemini and Cursor Agent based on updates from turtton/dotnix.
